version: '3'
services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3307:3306
    volumes:
      - database-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: patient

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db

  notes:
    build:
      context: ./notes/
      dockerfile: Dockerfile
    image:  dlugi57/notes
    container_name: notes
    ports:
      - "8086:8086"

    restart: always

  patient:
    build:
      context: ./patient/
      dockerfile: Dockerfile
    image: dlugi57/patient
    container_name: patient
    ports:
      - "8084:8084"

    restart: always

  report:
    environment:
      - NOTE_BASE_URL=http://notes:8086
      - PATIENT_BASE_URL=http://patient:8084
    build:
      context: ./report/
      dockerfile: Dockerfile
    image: dlugi57/report
    container_name: report
    ports:
      - "8085:8085"

    depends_on:
      - notes
      - patient

    restart: always

volumes:
  database-volume:
  mongo-volume: